# Add this line at the VERY TOP to fix the "Unknown tag" error
minimal_mistakes_external_repository: true

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
title: "***Rifat Chronicles***"
url: "https://rifat-chronicles.github.io"
baseurl: ""

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
