remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
title: "Rifat Chronicles"
url: "https://rifat-chronicles.github.io"
baseurl: ""

# This makes the "Home/About" buttons work
modules:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
