remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
title: "***Rifat Chronicles***"
description: "**Ph.D. Research & Global Travels**"
url: "https://rifat-chronicles.github.io"
baseurl: ""

# This tells GitHub to use the "Beautiful" layout for all your blogs
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
