# Fix for the "include_cached" build error
minimal_mistakes_external_repository: true

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
title: "***Rifat Chronicles***"
url: "https://rifat-chronicles.github.io"
baseurl: ""

# This creates your beautiful sidebar
author:
  name: "Rifat"
  bio: "***PhD Student at Rutgers | Wireless Researcher***"
  location: "Highland Park, NJ"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
